export const SERVICES = [
  {
    id: "corporate-travel-solutions",
    category: "special-services",
    title: "Corporate Travel",
    images: [
      "Corporate Travels (2).jpg",
      "Corporate Travels (1).jpg",
      "Corporate Travels (3).jpg",
    ],
    folderName: "services/Special Services/Corporate Travel Solutions/images",
    docxPath:
      "Special Services/Corporate Travel Solutions/Corporate Travel Solutions.docx",
  },
  {
    id: "event-management",
    category: "special-services",
    title: "Destination Weddings",
    images: ["Destination Wedding.jpg"],
    folderName: "services/Special Services/Event Management/images",
    docxPath: "Special Services/Event Management/Event Management.docx",
  },
  {
    id: "luxury-travel",
    category: "special-services",
    title: "Luxury Travel",
    images: ["Luxury Travels.jpg"],
    folderName: "services/Special Services/Luxury Travel/images",
    docxPath: "Special Services/Luxury Travel/Luxury Travel.docx",
  },
  {
    id: "mice",
    category: "special-services",
    title: "MICE Travel",
    images: ["Mice Travels (1).jpg", "Mice Travels (2).jpg"],
    folderName: "services/Special Services/MICE/images",
    docxPath: "Special Services/MICE/MICE.docx",
  },
  {
    id: "passport-services",
    category: "travel-documentation",
    title: "Passport Services",
    images: ["Passport services.jpg"],
    folderName: "services/Travel Documentation/Passport Services/images",
    docxPath: "Travel Documentation/Passport Services/Passport Services.docx",
  },
  {
    id: "travel-insurance",
    category: "travel-documentation",
    title: "Travel Insurance",
    images: ["Travel Insurance.jpg"],
    folderName: "services/Travel Documentation/Travel Insurance",
    docxPath: "Travel Documentation/Travel Insurance/Travel Insurance.docx",
  },
  {
    id: "eurorail-tickets",
    category: "travel-essentials",
    title: "Eurail",
    images: [
      "Eurail (10).jpeg",
      "Eurorail (1).jpg",
      "Eurorail (2).jpg",
      "Eurorail (3).jpg",
      "Eurorail (4).jpg",
      "Eurorail (5).jpg",
      "Eurorail (6).jpg",
      "Eurorail (7).jpg",
      "Eurorail (8).jpg",
      "Eurorail (9).jpg",
    ],
    folderName: "services/Travel Essentials/Eurorail Tickets/images",
    docxPath: "Travel Essentials/Eurorail Tickets/Eurorail Tickets.docx",
  },
  {
    id: "flight-tickets",
    category: "travel-essentials",
    title: "Flight Ticket Booking",
    images: ["Flight Ticket Booking.png"],
    folderName: "services/Travel Essentials/Flight Tickets/images",
    docxPath: "Travel Essentials/Flight Tickets/Flight Tickets.docx",
    airlineLogos: [
      "Aegean-Airlines-logo.png",
      "Aeroflot-Logo.png",
      "Air-Arabia-logo-500x281.png",
      "Air-Astana-logo-500x281.png",
      "Air-Austral-Logo.png",
      "Air-Berlin-logo.png",
      "Air-Canada-Logo.png",
      "Air-France-Logo.png",
      "Air-Hong-Kong-Logo-500x281.png",
      "Air-India-Express-logo-500x324.png",
      "Air-India-Logo.png",
      "Air-Luxor-Logo-500x281.png",
      "American-Airlines-Logo.png",
      "BA-Connect-Logo.png",
      "Biman-Bangladesh-Airlines-Logo.png",
      "British-Airways-Logo.png",
      "Brussels-Airlines-Logo.png",
      "Cathay-Pacific-Logo.png",
      "China-Airlines-logo.png",
      "China-Eastern-Airlines-logo.png",
      "Delta-Air-Lines-Logo.png",
      "EgyptAir-Logo.png",
      "El-Al-Logo.png",
      "Emirates-Logo.png",
      "Ethiopian-Airlines-Logo.png",
      "Etihad-Airways-Logo.png",
      "Finnair-Logo.png",
      "FlyDubai-Logo.png",
      "Gulf-Air-logo.png",
      "Hong-Kong-Airlines-Logo.png",
      "KLM-logo.png",
      "Kenya-Airways-logo.png",
      "Korean-Air-Logo.png",
      "Kuwait-Airways-logo.png",
      "Lion-Air-Logo.png",
      "Logo-Boeing.png",
      "Lufthansa-Group-logo.png",
      "Luxair-Logo.png",
      "Malaysia-Airlines-Logo.png",
      "Malindo-logo.png",
      "Myanmar-Airways-International-Logo.png",
      "Qantas-Logo.png",
      "Qatar-Airways-Logo.png",
      "Royal-Brunei-Airlines-logo.png",
      "Royal-Jordanian-logo.png",
      "Saudi-Arabian-Airlines-Logo.png",
      "Scoot-Logo.png",
      "Singapore-Airlines-Logo.png",
      "Thai-Airways-Logo.png",
      "Turkish_Airlines_logo.png",
      "United-Airlines-Logo.png",
    ],
    logosFolder: "services/Travel Essentials/Flight Tickets/airline-logos",
  },
  {
    id: "hotel-bookings",
    category: "travel-essentials",
    title: "Hotel Booking",
    images: ["Hotel Booking.jpg"],
    folderName: "services/Travel Essentials/Hotel Bookings/images",
    docxPath: "Travel Essentials/Hotel Bookings/Hotel Bookings.docx",
  },
  {
    id: "visa-services",
    category: "travel-documentation",
    title: "Visa Services",
    label: "",
    saveText: "Hassle-Free",
    subtitle: "Visa Assistance for All Destinations!",
    buttonText: "Apply Today",
    images: ["visas.jpg"],
    folderName: "images/header_images",
    docxPath: "Travel Documentation/Visa Services/Visa Services.docx",
  },
];
